config/routes.rb
Rails.application.routes.draw do
  
  delete '/delete_user' => 'manage_users#destroy'
  
  post '/new_user' => 'manage_users#create'
  get '/new_user' => 'manage_users#new'
  

  get '/edit_user' => 'manage_users#edit'
  put '/edit_user' => 'manage_users#update'

  get 'users' => 'manage_users#index'

  get  'owner_items' => 'owner_items#index'

  resources :items
  devise_for :users

  root 'pages#home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  validates :name, :price, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items, dependent: :destroy

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :image_url) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :image_url, :password, :current_password) }
    end


  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :bounce_incorrect_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!,    only: [:new, :create, :edit, :update, :destroy]
  before_action :set_item,              only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.order(:price).paginate(page: params[:page], per_page: 15)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.create(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :image_url)
    end

    def bounce_incorrect_user
    if user_signed_in?
      unless current_user == set_item.user or current_user.admin?
        redirect_to @item, notice: "Not authorized; you are not the owner of this item"
      end
    else
      redirect_to new_user_session_url, notice: "Please sign in first"
    end
  end

end

app/controllers/manage_users_controller.rb
class ManageUsersController < ApplicationController
  before_action :bounce_if_last_admin, only: [:destroy]
	before_action :bounce_incorrect_user, only: [:destroy, :edit, :update]
	before_action :set_user, only: [:edit, :destroy, :update]

  def index
  	@users = User.all.order(:admin).order(:name).paginate(page: params[:page], per_page: 10)
  end

  def new
    @user=User.new
  end

  def edit
  end

  def destroy
  	@user.destroy
  	redirect_to users_url, notice: 'User was successfully deleted...'
  end

  # POST /items
  # POST /items.json
  def create
    @user = User.create(user_params_for_new)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'user was successfully created.' }
        format.json { render :show, status: :created, location: users_url }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @user.update(user_params_for_edit)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: users_url }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  private
  	def set_user
  		@user = User.find_by(id: params[:id])
  	end

  	def user_params_for_edit
      if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
        params.require(:user).permit(:name, :email, :image_url, :admin)
      else
        params.require(:user).permit(:name, :email, :image_url, :password, :password_confirmation, :admin)
      end
    end

    def user_params_for_new
      params.require(:user).permit(:name, :email, :image_url, :password, :password_confirmation, :admin)
    end

    def bounce_incorrect_user
    	if not user_signed_in?
    		redirect_to new_user_session_url, notice: "Sign in first please..."
    	else
    		redirect_to root_url, notice: "Sign in as admin please..." unless current_user.admin?
    	end
    end

    def bounce_if_last_admin
      if User.where(admin: true).count == 1
        redirect_to users_url, notice: "The last admin can not be deleted !!!"
      end
    end

end

app/controllers/owner_items_controller.rb
class OwnerItemsController < ApplicationController
  def index
  	@owner = User.find_by(id: params[:owner])
  	@items = Item.where(user_id: @owner.id).paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/manage_users_helper.rb
module ManageUsersHelper
end

app/helpers/owner_items_helper.rb
module OwnerItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= link_to 'Add new Item', new_item_path %>


<%= will_paginate @items, class: "pagin" %>

<table>

  <tbody>
    <% @items.each do |item| %>
  
      <tr class="<%= cycle('line-odd','line-even') %>">
        <% if user_signed_in? and current_user == item.user %>
          <tr class='line-user'>
        <% end %>
        <td class='img-cell'> <%= image_tag item.image_url, class: "catalog-image" %></td>
        <td><strong><%= item.name %></strong><br/>
          <%= truncate(item.description, length: 200) %><br/>
          <strong><%= number_to_currency(item.price) %> </strong><%= link_to "more details", item_path(item) %>
        </td>
        <td class='img-cell'>
          <strong>Owner</strong>
          <%= image_tag item.user.image_url, class: "user-image" %> <br>
          <%= link_to item.user.name, owner_items_url(owner: item.user) %>
        </td>
        <% if user_signed_in? and current_user.admin? %>
          <td>
            <%= link_to "edit", edit_item_path(item) %> <br>
            <%= link_to "delete", item_path(item), method: :delete  %> <br>
          </td>
        <% end %>
      </tr>

    <% end %>
  </tbody>
</table>

<%= will_paginate @items, class: "pagin" %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<%= image_tag(@item.image_url, class: "show-image") %>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @item.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<% if user_signed_in? and (current_user==@item.user or current_user.admin?) %>
  <strong><%= "This is one of your items" if current_user==@item.user %></strong> <br>
  <%= link_to "edit", edit_item_path(@item) %> <br>
  <%= link_to "delete", item_path(@item), method: :delete  %> <br>
<% end %>
<%= link_to 'All Items List', items_path %>


<p>
  <strong>Owner:</strong>
  <%= @item.user.name %> <br>
  <%= image_tag @item.user.image_url, class: 'user-image' %> <br>
  <%= link_to 'Items from this user', owner_items_path(owner: @item.user) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= controller.controller_name %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container"> 
			<%= link_to "Template App", root_url, id:'logo' %>
			<%= link_to "All Items", items_path, id:'catalog-logo' %>
			<%= link_to "All Users", users_path, id:'cart-logo' %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li><%= link_to "My Account", edit_user_registration_path %></li>
						<% if not current_user.admin? %>
							<li><%= link_to "My Items", owner_items_url(owner: current_user) %></li>
						<% end %>
					<% end %>
					<li><%= link_to "HOME", root_url %></li>
					<% if current_user %>
						<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
						<li><%= image_tag current_user.image_url, class: "user-image" if current_user %></li>
					<% else %>
						<li><%= link_to "Log in", new_user_session_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	
		<div class="container">
			<div id='info-bar'> 
				<%= [current_user.name, current_user.admin? ? 'admin' : 'user'] if current_user %>

			<% flash.each do |name, message| %>
				<% message = "You are already logged in. Log out first please..." if message=="You are already signed in." %>
				<% message = "Loged in successfully..." if message=="Signed in successfully." %>
				<% message = "Loged out successfully..." if message=="Signed out successfully." %>
				<div class="<%= name %>"><small><%= name.capitalize %></small>: <%= message %> </div>
			<% end %>
			</div>
		</div>
		<div class="container">
			
			 	<marquee id='marq'>... this is an experimental and demonstrative site ... </marquee>
			
		</div>

	</header>
	
	<div class="container">

		<%= yield %>

	</div>

</body>

</html>

app/views/manage_users/edit.html.erb
<h2>Edit User Account of "<%= @user.name %>" </h2>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @user, as: :user, url: edit_user_path(id: @user), method: :put do |f| %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url, autofocus: true, placeholder: "optional" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i> <br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>


  <div class="field">
    <%= f.check_box :admin %>
    <%= f.label :admin, 'make this user admin?' %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>

<% end %>

app/views/manage_users/index.html.erb
<% if user_signed_in? and current_user.admin? %> 
  <%= link_to "Add new user", new_user_url %> <br>
<% elsif not user_signed_in? %>
  <%= button_to "Sign up and try the site!", new_user_registration_path, method: :get, class: 'button-signup' %>
<% end %>

<h3>Listing All Users</h3>

<%= will_paginate @users, class: "pagin" %>

<table>
  <thead>
    <tr>
      <th> user image </th>
      <th> Name + Link to Items </th>
      <th> # items posted </th>
      <% if user_signed_in? and current_user.admin? %>
        <th> admin? </th>
        <th> manage </th>
        <th> email </th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <% if user.admin? %>
        <tr class="line-admin">
      <% else %>
        <tr class="<%= cycle('line-odd','line-even') %>">
      <% end %>
        <td class='img-cell'> <%= image_tag user.image_url, class: "user-image" %></td>
        <td><%= link_to user.name, owner_items_url(owner: user) %></td>
        <td><%= user.items.count %></td>
          <% if user_signed_in? and current_user.admin? %>
            <td><%= user.admin? %></td>
	          <td class='line-admin'>
	            <%= link_to "edit", edit_user_path(id: user) %> <br>
	            <%= link_to "delete", delete_user_path(id: user), method: :delete, data: {confirm: "Are you sure?"} %>
	          </td>
            <td>
              <%= user.email %> 
            </td>
	        <% end %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>

<%= will_paginate @users, class: "pagin" %>

app/views/manage_users/new.html.erb
<h2>New User Account </h2>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @user, as: :user, url: new_user_path(id: @user), method: :post do |f| %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url, autofocus: true, placeholder: "optional" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %> <br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.check_box :admin %>
    <%= f.label :admin, 'make this user admin?' %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>

<% end %>

app/views/owner_items/index.html.erb
<p><%= link_to 'Add new item', new_item_path if @owner == current_user %></p><br>

<h3> <%= image_tag @owner.image_url, class: "user-image" %>
Listing Items from user "<%= @owner.name %>"</h3>

<%= "no items posted" if @items.empty? %>

<%= will_paginate @items, class: "pagin" %>

<table>
  <!-- <thead>
    <tr>
      <th> image </th>
      <th> Name+Description+Price </th>
      <th> Seller name+email+ID </th>
      <th> Mark-It </th>
    </tr>
  </thead> -->

  <tbody>
    <% @items.each do |item| %>
  
      <tr class="<%= cycle('line-odd','line-even') %>">
        <td class='img-cell'> <%= image_tag item.image_url, class: "catalog-image" %></td>
        <td><strong><%= item.name %></strong><br/>
          <%= truncate(item.description, length: 200) %><br/>
          <strong><%= number_to_currency(item.price) %> </strong><%= link_to "more details", item_path(item) %>
          <% if user_signed_in? and (current_user == item.user or current_user.admin?) %>
	          <td>
	            <%= link_to "edit", edit_item_path(item) %> <br>
	            <%= link_to "delete", item_path(item), method: :delete  %> <br>
	          </td>
	        <% end %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>

<%= will_paginate @items, class: "pagin" %>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<%= link_to "Add/Edit Items", owner_items_url(owner: current_user) %>
<% else %>
	<%= button_to "Sign up and try the site!", new_user_registration_path, method: :get, class: 'button-signup' %> 
<% end %>

<h1>Welcome to Template App </h1>
<p> This is a template for a simple model depicted in below figure:</p>
<%= image_tag "model1.jpg", class: 'model' %> <br>
User features of this template is implemented by using rails gem <strong> "devise" </strong>.

<h3>Features</h3>
<ul> 
  <li> <strong> Users </strong> Users are oweners of the items. Only signed up users of the site can advertise and manage their items. Once they logged in, they will be able to add new items, edit and delete them; but they can not edit or delete the other items that they do not own (i.e. items that someone else posted to the site). User can also delete their own account if they want to do so. There is a user list that is puplic but only contains partial info of the users for privacy and security reasons </li>
  <li> <strong> Administrators </strong> As super users, admin users have more privileges. Once they logged in 1) They can see all the users and manage them (add/edit/delete) 2) They can see all the products and manage them (add/edit/delete) 3) They can see and edit other admins and they can manage each other. 4) Minumum number of admins is one. The last admin can not be deleted. </li>
  <li> <strong> Remembering the computer </strong> If chosen, the site remembers the computer for easy login by bypassing the login entry form. It remembers the user on the next site visit when the browser is closed by the user. When logged out the feature resets, meaning user has to login in next visit. </li>
  <li> <strong> Reset password feauture </strong> Forgetten password can be reset through automatic emailing from the site. </li>
  <li> <strong> Account activation feature </strong> Through automatic email corfirmation the account has to be activated </li>
</ul>